# Generated by Django 4.2.6 on 2024-01-27 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexperince',
            name='currently_working',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
