# Generated by Django 4.2.6 on 2024-01-27 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_workexperince_currently_working'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='graduation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
