# Generated by Django 4.2.6 on 2024-01-31 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workexperience',
            name='user',
        ),
        migrations.RemoveField(
            model_name='profiles',
            name='educations',
        ),
        migrations.RemoveField(
            model_name='profiles',
            name='job_title',
        ),
        migrations.RemoveField(
            model_name='profiles',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='profiles',
            name='work_experiences',
        ),
        migrations.AddField(
            model_name='profiles',
            name='purpose',
            field=models.CharField(choices=[('EMPLOYER', 'Employer'), ('CANDIDATES', 'Candidates'), ('FREELANCERS', 'Freelancers')], default='CANDIDATES', max_length=14),
        ),
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.DeleteModel(
            name='WorkExperience',
        ),
    ]
