# Generated by Django 4.2.6 on 2024-02-05 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Skills')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Job Title')),
                ('company', models.CharField(max_length=60, verbose_name='Company Name')),
                ('work_type', models.CharField(choices=[('Hybrid', 'Hybrid'), ('Remote', 'Remote'), ('On site', 'Onsite')], max_length=20)),
                ('job_type', models.CharField(choices=[('Fulltime', 'Fulltime'), ('Contract', 'Contract'), ('intenship', 'Intenship'), ('Par time', 'Parttime')], max_length=20)),
                ('description', models.TextField(help_text='Company Description, Role Description, Qualifications')),
                ('skills', models.ManyToManyField(to='job.skill')),
            ],
        ),
    ]
